title: Pfinztaler Barockkonzerte
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
place: Ev. Kirche Söllingen (Pfinztal)
latitude: 48.9855557
longitude: 8.5401293
prose:
  rooturl: '_posts'
  siteurl: 'http://lieselwaeppen.github.io/barockensemble/'
  relativeLinks: 'http://lieselwaeppen.github.io/barockensemble/links.jsonp'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          label: "Konzerttitel"
          element: "text"
          placeholder: "Konzerttitel"
      - name: "subtitle"
        field:
          element: "text"
          label: "Konzertort"
          placeholder: "Konzertort"
      - name: "date"
        field:
          element: "text"
          label: "Hat sich was geändert?"
          value: CURRENT_DATETIME
      - name: "author"
        field:
          element: "text"
          label: "Autor"
          value: "Admin"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
